name: 'Build Electron Apps'

on:
  push:
    # tags: [v**]
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            flags: '--mac'
            output: 'dist/*.dmg'
          # - os: windows-latest
          #   flags: "--win"
          #   output: "dist/*.exe"
          # - os: ubuntu-latest
          #   flags: "--linux"
          #   output: "dist/???"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build ${{ matrix.flags }}
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ matrix.output }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: nyaa8/package-version@v1
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          body: v${{ env.PACKAGE_VERSION }}
          draft: true
          prerelease: true
          tag: v${{ env.PACKAGE_VERSION }}
          token: ${{ secrets.github_token }}
